version: '3.6'
services:
  nginx:
    container_name: anime-nginx
    build:
      context: .
    ports:
      - '80:80'
    volumes:
      - ./logs:/var/log/nginx/
      - ./config/default1.conf:/etc/nginx/conf.d/default.conf
    restart: always

networks:
    default:
      name: anime-network
