version: "3.6"
services:
  nginx:
    container_name: anime-nginx
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx/
      - ./config/cloudflare.conf:/etc/nginx/conf.d/cloudflare.conf
      - ./config/pro.conf:/etc/nginx/conf.d/default.conf
      - ./google54bac24f055054ae.html:/usr/share/nginx/html/google54bac24f055054ae.html
    restart: always

networks:
  default:
    name: anime-network
